### ISSUE TITLE
Weather Observation Station 20

### ISSUE THREAD

**Issue by krishnasai21** [Thomas-George-T/HackerRank-SQL-Challenges-Solutions#11]
select 

round(sta.lat_n, 4) 

from station as sta 

where 

(select count(lat_n) from station where lat_n < sta.lat_n) = (select count(lat_n) from station where lat_n > sta.lat_n);

**Comment by Thomas-George-T** [comment]
Hey @krishnasai21, Thanks for the solution. I was proposing that you raise a pull request and not a new issue 😄 

By raising a new pull request, you highlight your contribution to this repository and get yourself added as a contributor.

Read more about raising a Pull Request from a fork here : [GitHub Docs](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)
