### ISSUE TITLE
Faster Code

### ISSUE THREAD

**Issue by jowinjestine** [Thomas-George-T/HackerRank-SQL-Challenges-Solutions#14]
As You have made changes to all SQL Basic Select to improve it, I did not see a change here so I am suggesting it.

select distinct city from station where not right(city,1) in('a','e','i','o','u')  is faster

**Comment by Thomas-George-T** [comment]
Thanks for bringing it to my notice. Could you raise a pull request, I don't remember the file at the moment. I can merge the PR if it looks alright
