### ISSUE TITLE
Answer was incomplete | Weather Observation Station 1

### ISSUE THREAD

**Issue by nottherightlynx** [Thomas-George-T/HackerRank-SQL-Challenges-Solutions#21]
missing ORDER BY command

SELECT city, state
FROM station
ORDER BY city,state;

**Comment by Thomas-George-T** [comment]
![image](https://user-images.githubusercontent.com/20851812/191910160-c752050e-4767-4bca-89ed-0e18a1e9d7a8.png)

The questions isn't asking for an Order By statement. The Answer is complete.
