### ISSUE TITLE
Weather Observation Station 3

### ISSUE THREAD

**Issue by Mimanatekar** [Thomas-George-T/HackerRank-SQL-Challenges-Solutions#9]
The given solution does not work, so try this instead:

SELECT DISTINCT CITY FROM STATION WHERE MOD(ID, 2) = 0;

**Comment by Thomas-George-T** [comment]
Hi,

The given solution does work. Please could you see that you're using MySQL? Please could you check again?

Please let me know

**Comment by Mimanatekar** [comment]
yes, I tried now, it works. Thanks.

**Comment by Thomas-George-T** [comment]
Great! Closing this issue.
